version: '2'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker-aws-test_development

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/docker-aws-test"
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - "db"
    links:
      - "db"
